# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/leviathan/dev/Biu

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/leviathan/dev/Biu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/leviathan/dev/Biu/CMakeFiles /home/leviathan/dev/Biu/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/leviathan/dev/Biu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named atendb

# Build rule for target.
atendb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 atendb
.PHONY : atendb

# fast build rule for target.
atendb/fast:
	$(MAKE) -f CMakeFiles/atendb.dir/build.make CMakeFiles/atendb.dir/build
.PHONY : atendb/fast

#=============================================================================
# Target rules for targets named db

# Build rule for target.
db: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 db
.PHONY : db

# fast build rule for target.
db/fast:
	$(MAKE) -f test/CMakeFiles/db.dir/build.make test/CMakeFiles/db.dir/build
.PHONY : db/fast

db/db_impl.o: db/db_impl.cc.o

.PHONY : db/db_impl.o

# target to build an object file
db/db_impl.cc.o:
	$(MAKE) -f CMakeFiles/atendb.dir/build.make CMakeFiles/atendb.dir/db/db_impl.cc.o
.PHONY : db/db_impl.cc.o

db/db_impl.i: db/db_impl.cc.i

.PHONY : db/db_impl.i

# target to preprocess a source file
db/db_impl.cc.i:
	$(MAKE) -f CMakeFiles/atendb.dir/build.make CMakeFiles/atendb.dir/db/db_impl.cc.i
.PHONY : db/db_impl.cc.i

db/db_impl.s: db/db_impl.cc.s

.PHONY : db/db_impl.s

# target to generate assembly for a file
db/db_impl.cc.s:
	$(MAKE) -f CMakeFiles/atendb.dir/build.make CMakeFiles/atendb.dir/db/db_impl.cc.s
.PHONY : db/db_impl.cc.s

file/posix_file.o: file/posix_file.cc.o

.PHONY : file/posix_file.o

# target to build an object file
file/posix_file.cc.o:
	$(MAKE) -f CMakeFiles/atendb.dir/build.make CMakeFiles/atendb.dir/file/posix_file.cc.o
.PHONY : file/posix_file.cc.o

file/posix_file.i: file/posix_file.cc.i

.PHONY : file/posix_file.i

# target to preprocess a source file
file/posix_file.cc.i:
	$(MAKE) -f CMakeFiles/atendb.dir/build.make CMakeFiles/atendb.dir/file/posix_file.cc.i
.PHONY : file/posix_file.cc.i

file/posix_file.s: file/posix_file.cc.s

.PHONY : file/posix_file.s

# target to generate assembly for a file
file/posix_file.cc.s:
	$(MAKE) -f CMakeFiles/atendb.dir/build.make CMakeFiles/atendb.dir/file/posix_file.cc.s
.PHONY : file/posix_file.cc.s

util/arena.o: util/arena.cc.o

.PHONY : util/arena.o

# target to build an object file
util/arena.cc.o:
	$(MAKE) -f CMakeFiles/atendb.dir/build.make CMakeFiles/atendb.dir/util/arena.cc.o
.PHONY : util/arena.cc.o

util/arena.i: util/arena.cc.i

.PHONY : util/arena.i

# target to preprocess a source file
util/arena.cc.i:
	$(MAKE) -f CMakeFiles/atendb.dir/build.make CMakeFiles/atendb.dir/util/arena.cc.i
.PHONY : util/arena.cc.i

util/arena.s: util/arena.cc.s

.PHONY : util/arena.s

# target to generate assembly for a file
util/arena.cc.s:
	$(MAKE) -f CMakeFiles/atendb.dir/build.make CMakeFiles/atendb.dir/util/arena.cc.s
.PHONY : util/arena.cc.s

util/coding.o: util/coding.cc.o

.PHONY : util/coding.o

# target to build an object file
util/coding.cc.o:
	$(MAKE) -f CMakeFiles/atendb.dir/build.make CMakeFiles/atendb.dir/util/coding.cc.o
.PHONY : util/coding.cc.o

util/coding.i: util/coding.cc.i

.PHONY : util/coding.i

# target to preprocess a source file
util/coding.cc.i:
	$(MAKE) -f CMakeFiles/atendb.dir/build.make CMakeFiles/atendb.dir/util/coding.cc.i
.PHONY : util/coding.cc.i

util/coding.s: util/coding.cc.s

.PHONY : util/coding.s

# target to generate assembly for a file
util/coding.cc.s:
	$(MAKE) -f CMakeFiles/atendb.dir/build.make CMakeFiles/atendb.dir/util/coding.cc.s
.PHONY : util/coding.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... atendb"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... install"
	@echo "... db"
	@echo "... db/db_impl.o"
	@echo "... db/db_impl.i"
	@echo "... db/db_impl.s"
	@echo "... file/posix_file.o"
	@echo "... file/posix_file.i"
	@echo "... file/posix_file.s"
	@echo "... util/arena.o"
	@echo "... util/arena.i"
	@echo "... util/arena.s"
	@echo "... util/coding.o"
	@echo "... util/coding.i"
	@echo "... util/coding.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

